# A string used to distinguish different Supabase projects on the same machine.
# Not particularly important.
project_id = "youth-dreamers-foundation"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used
# in emails.
site_url = "http://localhost:5173"
# A list of *exact* URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = ["https://localhost:5173"]
# How long tokens are valid for, in seconds. Defaults to 3600 (1 hour), maximum 604800 (1 week).
jwt_expiry = 3600
# If disabled, the refresh token will never expire.
refresh_token_rotation_enabled = true
# Allows refresh tokens to be reused after expiry, up to the specified interval in seconds.
# Requires refresh_token_rotation_enabled to be false.
refresh_token_reuse_interval = 10
# Allow/disallow new user signups to your project.
enable_signup = true

[auth.email]
# Allow/disallow new user signups via email to your project.
enable_signup = true
# If enabled, a user will be required to confirm any email change on both the old, and new email addresses.
# If disabled, only the new email is required to confirm.
double_confirm_changes = true
# If enabled, users need to confirm their email address before signing in.
enable_confirmations = false

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost:54321"

[inbucket]
enabled = true
port = 54324
# Uncomment to expose additional ports for testing user applications that send emails.
# smtp_port = 54325
# pop3_port = 54326

[storage]
enabled = true
# The maximum file size allowed (e.g. "5MB", "500KB").
file_size_limit = "50MiB"

[edge_runtime]
enabled = true
port = 54325

[analytics]
enabled = false
port = 54327
vector_port = 54328
# Setup BigQuery project to use analytics.
# gcp_project_id = ""
# gcp_project_number = ""
# gcp_jwt_path = "supabase/gcloud.json"

[functions]
# A mapping of function names to their corresponding Docker image.
[functions.hello-world]
verify_jwt = false